version: '3.8'

services:
  ollama-api:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    environment:
      - MODEL=llama3.2
    ports:
      - "5001:5000"
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    environment:
      STREAMLIT_SERVER_HEADLESS: true
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - ollama-api
    restart: always
